---
title: "Prepare Health Survey for England data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Prepare Health Survey for England data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
bibliography: refs/smoking_transitions.bib
link-citations: yes
citation_package: natbib
biblio-style: vancouver
urlcolor: blue
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.pos = 'H'
)
```


Here is a guide to setting up the Health Survey for England data to work with the `smktrans` package.    

**Step 1: Read and clean the data**   

```{r readclean, eval = F}

# Process tobacco from the Health Survey for England
# retaining variables needed for estimation of smoking transition probabilities

# hseclean version 1.0.0

library(hseclean)
library(magrittr)
library(data.table)

root_dir <- "/Volumes/Shared/"

# apply functions to create the variables for analysis and to retain only the required variables

# The variables to retain
keep_vars = c(
  # Survey design variables
  "wt_int",
  "psu",
  "cluster",
  "year",
  
  # Social / economic / demographic variables
  "age",
  "age_cat",
  "sex",
  "imd_quintile",
  "degree",
  "relationship_status",
  "kids",
  "employ2cat",
  "income5cat",
  
  # Long term health conditions
  "hse_mental",
  
  # Smoking
  "cig_smoker_status",
  "years_since_quit", "years_reg_smoker", "cig_ever",
  "smk_start_age", "smk_stop_age", "censor_age"

)

# The variables that must have complete cases
complete_vars <- c("age", "sex", "imd_quintile", "year", "psu", "cluster", "cig_smoker_status", "censor_age")


#-----------------------------------------------------
# Read and clean the data

cleandata <- function(data) {
  
  data %<>%
    clean_age %>%
    clean_demographic %>% 
    clean_education %>%
    clean_economic_status %>%
    clean_family %>%
    clean_income %>%
    clean_health_and_bio %>%
    smk_status %>%
    smk_former %>%
    smk_quit %>%
    smk_life_history %>%
    smk_amount %>%
    
    select_data(
      ages = 8:89,
      years = 2001:2016,
      
      # variables to retain
      keep_vars = keep_vars,
      
      # The variables that must have complete cases
      complete_vars = complete_vars
    )
  
  return(data)
}

# Read and clean each year of data and bind them together in one big dataset
data <- combine_years(list(
  cleandata(read_2001(root = root_dir)),
  cleandata(read_2002(root = root_dir)),
  cleandata(read_2003(root = root_dir)),
  cleandata(read_2004(root = root_dir)),
  cleandata(read_2005(root = root_dir)),
  cleandata(read_2006(root = root_dir)),
  cleandata(read_2007(root = root_dir)),
  cleandata(read_2008(root = root_dir)),
  cleandata(read_2009(root = root_dir)),
  cleandata(read_2010(root = root_dir)),
  cleandata(read_2011(root = root_dir)),
  cleandata(read_2012(root = root_dir)),
  cleandata(read_2013(root = root_dir)),
  cleandata(read_2014(root = root_dir)),
  cleandata(read_2015(root = root_dir)),
  cleandata(read_2016(root = root_dir))
))

# clean the survey weights
data <- clean_surveyweights(data)

# remake age categories
data[, age_cat := c("11-15",
                    "16-17",
                    "18-24",
                    "25-34",
                    "35-44",
                    "45-54",
                    "55-64",
                    "65-74",
                    "75-89")[findInterval(age, c(-1, 16, 18, 25, 35, 45, 55, 65, 75, 1000))]]

setnames(data,
         c("smk_start_age", "cig_smoker_status", "years_since_quit"),
         c("start_age", "smk.state", "time_since_quit"))

write.table(data, "article/outputs/HSE_2001_to_2016.csv", row.names = FALSE, sep = ",")

```

**Step 2: Impute missing values**   

```{r impute, eval = F}


# This code reads the processed HSE datasets for each year
# and conducts imputation.

# all the variables to be imputed are categorical

library(data.table)

# Load the data
data <- fread("article/outputs/HSE_2001_to_2016.csv")

# view variables with missingness
misscheck <- function(var) {
  x <- table(var, useNA = "ifany")
  na <- x[which(is.na(names(x)))]
  if(length(na) == 0) na <- 0
  perc <- round(100 * na / sum(x), 2)
  #return(c(paste0(na, " missing obs, ", perc, "%")))
  return(na)
}

n_missing <- sapply(data, misscheck)
missing_vars <- n_missing[which(n_missing > 0)]
missing_vars

# quick fixes to missing data
data[is.na(hse_mental) & age < 16, hse_mental := "no_mental"]

# household equivalised income has the most missingness 
# - this is a key variable to impute
# as we will use it to understand policy inequalities

# Set order of factors where needed for imputing as ordered.
data[ , kids := factor(kids, levels = c("0", "1", "2", "3+"))]
data[ , income5cat := factor(income5cat, levels = c("1_lowest_income", "2", "3", "4", "5_highest_income"))]

# Impute missing values

# Run the imputation
imp <- impute_data_mice(
  data = data,
  var_names = c(
    "sex",
    "age_cat",
    "kids",
    "relationship_status",
    "imd_quintile",
    "degree",
    "employ2cat",
    "income5cat",
    "hse_mental",
    "smk.state"
  ),
  var_methods = c(
    "",
    "",
    "polr",
    "polyreg",
    "",
    "logreg",
    "",
    "polr",
    "logreg",
    ""
  ),
  n_imputations = 1 
  # for testing just do 1 imputation
  # but test with more later
  # for point estimates, apparently 2-10 imputations are enough
)

data_imp <- copy(imp$data)

write.table(data_imp, "article/outputs/HSE_2001_to_2016_imputed.csv", row.names = FALSE, sep = ",")


# Do some sense checks on the imputation

# Does income (with the most missingness) align with index of multiple deprivation
data[ , .N, by = c("income5cat", "imd_quintile")]
setorderv(data_imp[ , .N, by = c("income5cat", "imd_quintile")], "N", -1)[]

```
