---
title: "Get started"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Get started}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

See the [methodology report](https://stapm.gitlab.io/projects/smoking-model-development/stpm_tech_report/stpm-technical-report.pdf).  

To illustrate the use of the `smktrans` functions to estimate smoking state transition probabilities, we have created example workflows. You can use these examples to help understand how the code works, run them to generate model inputs, or use them as a starting point for the development of a new project.    

At the moment, these workflows are accessible only to the project team. To access them, you will need to be added to the STAPM Gitlab organisation.  

The workflows are listed below:  

- [English national smoking transition probabilities](https://gitlab.com/stapm/projects/smoking-model-development/smoking_transitions_paper): main development repo for testing and validating the method to estimate the smoking transition probabilities.    

- [Forecast of future smoking trends - Royal College of Physican's report 2021](https://gitlab.com/stapm/projects/RCP_smoking_trends): 'src/20_estimate_smoking_transition_probabilities.R'.

- [Smoking transition probability inputs to tax policy modelling](https://gitlab.com/stapm/example-workflows/tax_policy_modelling): the entire workflow is implemented in the 'build inputs' folder, with an associated presentation that illustrates the outputs.     






